// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateReport(arg1) {
  return window['go']['wailsiface']['AnalysisService']['GenerateReport'](arg1);
}
