// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsiface} from '../models';

export function GenerateReport(arg1:string):Promise<wailsiface.ReportDTO>;
