// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsiface} from '../models';

export function QueryAssistant(arg1:wailsiface.AssistantQueryInput):Promise<wailsiface.AssistantResultDTO>;
