// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueryAssistant(arg1) {
  return window['go']['wailsiface']['AssistantService']['QueryAssistant'](arg1);
}
