// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListMatches(arg1) {
  return window['go']['wailsiface']['MatchService']['ListMatches'](arg1);
}

export function RefreshMatches(arg1) {
  return window['go']['wailsiface']['MatchService']['RefreshMatches'](arg1);
}
