// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsiface} from '../models';

export function ListMatches(arg1:string):Promise<Array<wailsiface.MatchDTO>>;

export function RefreshMatches(arg1:wailsiface.RefreshMatchesInput):Promise<wailsiface.RefreshMatchesResult>;
