// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentPlayer() {
  return window['go']['wailsiface']['PlayerService']['GetCurrentPlayer']();
}

export function LookupPlayer(arg1) {
  return window['go']['wailsiface']['PlayerService']['LookupPlayer'](arg1);
}
