// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsiface} from '../models';

export function GetCurrentPlayer():Promise<wailsiface.PlayerDTO>;

export function LookupPlayer(arg1:wailsiface.LookupPlayerInput):Promise<wailsiface.LookupPlayerResult>;
