// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LatestRank(arg1) {
  return window['go']['wailsiface']['RankService']['LatestRank'](arg1);
}

export function RefreshRank(arg1) {
  return window['go']['wailsiface']['RankService']['RefreshRank'](arg1);
}
