// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsiface} from '../models';

export function LatestRank(arg1:string):Promise<wailsiface.RankDTO>;

export function RefreshRank(arg1:wailsiface.RefreshRankInput):Promise<wailsiface.RefreshRankResult>;
