// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ResetAllData() {
  return window['go']['wailsiface']['SettingsService']['ResetAllData']();
}

export function Startup(arg1) {
  return window['go']['wailsiface']['SettingsService']['Startup'](arg1);
}
