// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsiface} from '../models';
import {context} from '../models';

export function ClearExpiredCache():Promise<wailsiface.ClearCacheResult>;

export function ExportLocalData():Promise<wailsiface.ExportDataResult>;

export function GetSettings():Promise<wailsiface.SettingsDTO>;

export function ResetAllData():Promise<wailsiface.ResetResult>;

export function SaveSettings(arg1:wailsiface.SaveSettingsInput):Promise<wailsiface.SettingsDTO>;

export function Startup(arg1:context.Context):Promise<void>;
