// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearExpiredCache() {
  return window['go']['wailsiface']['SettingsService']['ClearExpiredCache']();
}

export function ExportLocalData() {
  return window['go']['wailsiface']['SettingsService']['ExportLocalData']();
}

export function GetSettings() {
  return window['go']['wailsiface']['SettingsService']['GetSettings']();
}

export function ResetAllData() {
  return window['go']['wailsiface']['SettingsService']['ResetAllData']();
}

export function SaveSettings(arg1) {
  return window['go']['wailsiface']['SettingsService']['SaveSettings'](arg1);
}

export function Startup(arg1) {
  return window['go']['wailsiface']['SettingsService']['Startup'](arg1);
}
