// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsiface} from '../models';
import {context} from '../models';

export function SetAssistantOverlay(arg1:boolean):Promise<wailsiface.WindowModeResult>;

export function Startup(arg1:context.Context):Promise<void>;
