// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetAssistantOverlay(arg1) {
  return window['go']['wailsiface']['WindowService']['SetAssistantOverlay'](arg1);
}

export function Startup(arg1) {
  return window['go']['wailsiface']['WindowService']['Startup'](arg1);
}
