// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analysis} from '../models';
import {wailsiface} from '../models';

export function AnalyzeSnapshot(arg1:analysis.PlayerSnapshot):Promise<analysis.Report>;

export function FetchLiveReport():Promise<wailsiface.LiveAnalysisResult>;

export function GenerateDemoReport():Promise<analysis.Report>;

export function GetLastReport():Promise<wailsiface.LastReportResult>;
