// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeSnapshot(arg1) {
  return window['go']['wailsiface']['AnalysisService']['AnalyzeSnapshot'](arg1);
}

export function FetchLiveReport() {
  return window['go']['wailsiface']['AnalysisService']['FetchLiveReport']();
}

export function GenerateDemoReport() {
  return window['go']['wailsiface']['AnalysisService']['GenerateDemoReport']();
}

export function GetLastReport() {
  return window['go']['wailsiface']['AnalysisService']['GetLastReport']();
}
