// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {assistant} from '../models';

export function GetSessionState():Promise<assistant.SessionState>;

export function MarkRoundStart():Promise<assistant.TipResult>;

export function PollAutoTip():Promise<assistant.TipResult>;

export function RequestTip():Promise<assistant.TipResult>;

export function StartSession():Promise<assistant.SessionState>;

export function StopSession():Promise<assistant.SessionState>;
