// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSessionState() {
  return window['go']['wailsiface']['AssistantService']['GetSessionState']();
}

export function MarkRoundStart() {
  return window['go']['wailsiface']['AssistantService']['MarkRoundStart']();
}

export function PollAutoTip() {
  return window['go']['wailsiface']['AssistantService']['PollAutoTip']();
}

export function RequestTip() {
  return window['go']['wailsiface']['AssistantService']['RequestTip']();
}

export function StartSession() {
  return window['go']['wailsiface']['AssistantService']['StartSession']();
}

export function StopSession() {
  return window['go']['wailsiface']['AssistantService']['StopSession']();
}
