// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlayerInfo() {
  return window['go']['wailsiface']['AuthService']['GetPlayerInfo']();
}

export function IsLoggedIn() {
  return window['go']['wailsiface']['AuthService']['IsLoggedIn']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['wailsiface']['AuthService']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['wailsiface']['AuthService']['Logout']();
}
