// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsiface} from '../models';

export function GetPlayerInfo():Promise<wailsiface.RiotPlayerInfo>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<wailsiface.RiotLoginResult>;

export function Logout():Promise<void>;
