// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['wailsiface']['ChatService']['GetState']();
}

export function IsAvailable() {
  return window['go']['wailsiface']['ChatService']['IsAvailable']();
}

export function Reset() {
  return window['go']['wailsiface']['ChatService']['Reset']();
}

export function SendMessage(arg1) {
  return window['go']['wailsiface']['ChatService']['SendMessage'](arg1);
}
