// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsiface} from '../models';

export function GetState():Promise<wailsiface.ChatState>;

export function IsAvailable():Promise<boolean>;

export function Reset():Promise<wailsiface.ChatState>;

export function SendMessage(arg1:string):Promise<wailsiface.ChatState>;
