// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishPracticeSession(arg1) {
  return window['go']['wailsiface']['PracticeService']['FinishPracticeSession'](arg1);
}

export function GetPracticeProgress() {
  return window['go']['wailsiface']['PracticeService']['GetPracticeProgress']();
}

export function GetPracticeSessions() {
  return window['go']['wailsiface']['PracticeService']['GetPracticeSessions']();
}

export function ResetPracticeProgress() {
  return window['go']['wailsiface']['PracticeService']['ResetPracticeProgress']();
}

export function SetPracticeProgress(arg1, arg2) {
  return window['go']['wailsiface']['PracticeService']['SetPracticeProgress'](arg1, arg2);
}
