// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {practice} from '../models';
import {localstore} from '../models';

export function FinishPracticeSession(arg1:practice.SessionInput):Promise<practice.SessionState>;

export function GetPracticeProgress():Promise<localstore.PracticeProgressState>;

export function GetPracticeSessions():Promise<practice.SessionState>;

export function ResetPracticeProgress():Promise<localstore.PracticeProgressState>;

export function SetPracticeProgress(arg1:string,arg2:boolean):Promise<localstore.PracticeProgressState>;
