// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {henrik} from '../models';
import {settings} from '../models';

export function GetAPIStatus():Promise<henrik.Status>;

export function GetDataSettings():Promise<settings.DataSettings>;

export function SaveDataSettings(arg1:settings.DataSettings):Promise<settings.DataSettings>;
