// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAPIStatus() {
  return window['go']['wailsiface']['SettingsService']['GetAPIStatus']();
}

export function GetDataSettings() {
  return window['go']['wailsiface']['SettingsService']['GetDataSettings']();
}

export function SaveDataSettings(arg1) {
  return window['go']['wailsiface']['SettingsService']['SaveDataSettings'](arg1);
}
