// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tactical} from '../models';

export function DeleteMapPlan(arg1:string):Promise<void>;

export function ListMaps():Promise<Array<tactical.MapCatalogEntry>>;

export function LoadMapPlan(arg1:string):Promise<tactical.MapPlan>;

export function SaveMapPlan(arg1:tactical.MapPlan):Promise<tactical.MapPlan>;
