// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMapPlan(arg1) {
  return window['go']['wailsiface']['TacticalService']['DeleteMapPlan'](arg1);
}

export function ListMaps() {
  return window['go']['wailsiface']['TacticalService']['ListMaps']();
}

export function LoadMapPlan(arg1) {
  return window['go']['wailsiface']['TacticalService']['LoadMapPlan'](arg1);
}

export function SaveMapPlan(arg1) {
  return window['go']['wailsiface']['TacticalService']['SaveMapPlan'](arg1);
}
